### ISSUE TITLE
Remove non use module eradius_log.erl

### ISSUE THREAD

**Issue by vkatsuba** [travelping/eradius#185]
## `eradius` version
[2.2.1](https://github.com/travelping/eradius/releases/tag/2.2.1)

## Description
The `eradius` currently contains a module `eradius_log.erl` which used in few places for logging but at the same time in `eradius` used [logger](https://erlang.org/doc/man/logger.html) for logging. Looks like It's no make sense to use two different logging.

## Current behavior
The `eradius` use `eradius_log.erl` and [logger](https://erlang.org/doc/man/logger.html) for logging.

## Expected behavior
The `eradius_log.erl` removed from  `eradius` and used only [logger](https://erlang.org/doc/man/logger.html) for logging.

**Comment by RoadRunnr** [comment]
I think this ticket is invalid.

radius_log is implementing a traditional RADIUS log format. There are plenty of tools available to work on that format.
A user of the library therefore might find that log format useful.

**Comment by vkatsuba** [comment]
Closed after discussion with @RoadRunnr.
