### ISSUE TITLE
eradius don't started

### ISSUE THREAD

**Issue by apofiget** [travelping/eradius#39]
eradius application don't stared with error:
```Erlang
 {error,{{shutdown,{failed_to_start_child,dict,
                                          {function_clause,[{filename,join,
                                                                      [{error,bad_name},"dictionary.map"],
                                                                      [{file,"filename.erl"},{line,406}]},
                                                            {eradius_dict,'-do_load_tables/2-fun-0-',2,
                                                                          [{file,"src/eradius_dict.erl"},{line,78}]},
                                                            {lists,flatmap,2,[{file,"lists.erl"},{line,1248}]},
                                                            {eradius_dict,do_load_tables,2,
                                                                          [{file,"src/eradius_dict.erl"},{line,77}]},
                                                            {eradius_dict,init,1,
                                                                          [{file,"src/eradius_dict.erl"},{line,54}]},
                                                            {gen_server,init_it,6,[{file,[...]},{line,...}]},
                                                            {proc_lib,init_p_do_apply,3,[{file,...},{...}]}]}}},
         {eradius,start,[normal,[]]}}}]
```
start it as:
```Erlang
[application:ensure_started(A) || A <- [syntax_tools, compiler, goldrush, lager, crypto, eradius]].
```

Erlang/OTP 17, erts-6.2, VM started as:
```Erlang
erl -pa ebin deps/*/ebin -sname rad -config example.config
```

**Comment by liveforeverx** [comment]
Hi! @apofiget did you renamed the folder, where `eradius` located to something like `eradius_foobar`?

**Comment by apofiget** [comment]
Hi!
No, folder, where sources placed, named originally - eradius.
I'm just make git clone eradius, and then execute:
cd eradius && rebar get-deps && rebar complie 
and then try run VM.

**Comment by liveforeverx** [comment]
@apofiget I need more information for reproducing the issue:

That, what happens by me:

```
git clone git@github.com:travelping/eradius.git && cd eradius && rebar get-deps && rebar compile && rebar sh
[...]
==> eradius (shell)
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.0  (abort with ^G)
1> application:ensure_all_started(eradius).
13:10:20.042 [info] Application lager started on node nonode@nohost
13:10:20.103 [info] Loaded RADIUS tables: [dictionary]
13:10:20.494 [info] Application eradius started on node nonode@nohost
{ok,[syntax_tools,compiler,goldrush,lager,eradius]}
```

Started, without a problems

The real issue is, that something wrong with adding your application directory to code directories.

That, what you will get, if tries to get priv dir of an application:

```
1> code:priv_dir(eradius).
{error,bad_name}
```

That happens, if eradius folder is renamed(that all chars before `-` doesn't match `eradius`) or if, you simple doesn't add eradius, but added beams to yours code location. (Something like `code:add_path("ebin")`) without adding the whole application to code loader.

**Comment by apofiget** [comment]
@liveforeverx start shell as `rebar sh` and then start eradius solved this issue.
But something strange in this situation. As described in rebar help, '``rebar sh``' run erlang shell as: 
``erl -pa ebin -pa deps/*/ebin``
Ok, i tried start shell like it doing rebar(``erl -pa ebin -pa ebin/*/deps``) , then tried start eradius and i'm got a same error as described above. Maybe rebar add some other arguments when start shell?

**Comment by apofiget** [comment]
@liveforeverx I was found chages: ``rebar sh`` add absolute paths to source folders, like:
```Erlang
1> code:get_path().
["/somedir/soft/erlang/eradius/deps/goldrush/ebin",
 "/somedir/soft/erlang/eradius/deps/coveralls/ebin",
 "/somedir/soft/erlang/eradius/deps/meck/ebin",
 "/somedir/soft/erlang/eradius/deps/lager/ebin",
 "/somedir/local/bin/rebar/rebar/ebin","/usr/local/bin/rebar",
 "/somedir/soft/erlang/eradius/."
...
```
but if i'm start VM as ``erl -pa ebin -pa deps/*/ebin``, codeserver have a relative paths:
```Erlang
1> code:get_path().
["deps/meck/ebin",
"deps/lager/ebin",
"deps/goldrush/ebin",
"deps/coveralls/ebin",
"ebin","."
...
```
and this, as i think, causes a error. For details will look codeserver sources. Thanks!

**Comment by liveforeverx** [comment]
Yes, the `code_server` can find eradius application from path: "/somedir/soft/erlang/eradius/.", but can't find eradius application from path "." - thats is.
