### ISSUE TITLE
send_remote_request bug

### ISSUE THREAD

**Issue by 0xAX** [travelping/eradius#45]
It seems that the `eradius_client:send_remite_request_bug/4` function contains a bug. We are passing a `radius_request` to the `send_remote_request_loop` function as fifth parameter. For now this parameter can be plain `radius_request` or encoded request depends on the `get_remote_version` value:

```erlang
Request2 = case eradius_node_mon:get_remote_version(Node) of
                           {0, Minor} when Minor < 6 ->
                               eradius_lib:encode_request(Request1);
                           _ ->
                               Request1
                       end,
SenderPid = spawn(Node, ?MODULE, send_remote_request_loop, [self(), Socket, ReqId, {IP, Port}, Request2, Options]),
```
which is end up will call `send_request_loop/5`. The problem that the `send_request_loop/5` has clause only for non-encoded `radius_request`.

**Comment by liveforeverx** [comment]
Check any version, which exists before `0.6.0`, it was made to be compatible with older versions, which accepts only encoded radius request (it is done for example, that you can run 0.6.0 version with remote 0.4.0 eradius version, which have older codebase).

**Comment by liveforeverx** [comment]
related pull request: https://github.com/travelping/eradius/pull/10
