### ISSUE TITLE
Client NasIds in Metrics

### ISSUE THREAD

**Issue by GalaxyGorilla** [travelping/eradius#59]
Currently Clients cannot be identified to the NAS they connect to. This should be changed such that metrics handling gets easier.

**Comment by hwinkel** [comment]
The Classic RADIUS MIB defines here metrics per ClientEntry (a RADIUS Client) identified by index (as usual in SNMP) and the IPAddress as String. In pure RADIUS a NAD is identified by IP and seldom by NAS-IDentifier (i.e. in the case of dynamic IPs of the client.

Reference MIB:

https://tools.ietf.org/html/rfc2619

**Comment by GalaxyGorilla** [comment]
I'm currently working on the metrics stuff in eradius and I implemented both possibilities (PR coming tomorrow). IMHO an ID is very useful for to generate deployment unspecific configs. That's atm the reason I want them.

**Comment by hwinkel** [comment]
NasId could be jusz an Id, right.Like the SNMP table Index

**Comment by GalaxyGorilla** [comment]
fixed with #65
